// Generates static theme CSS from the typed theme sources.
import { writeFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { generateThemeCSS } from "@astryxdesign/core/theme";
import { academicTheme } from "../src/theme/academic.ts";
import { terminalTheme } from "../src/theme/terminal.ts";

function renderThemeCss(theme, bootstrapSelector) {
  const { prose, component } = generateThemeCSS(theme);
  const themeSelector = `[data-astryx-theme="${theme.name}"]`;
  const bootstrapProse = bootstrapSelector
    ? prose?.replaceAll(themeSelector, bootstrapSelector)
    : "";
  const bootstrapComponent = bootstrapSelector
    ? component?.replaceAll(themeSelector, bootstrapSelector)
    : "";

  return `/* @generated by scripts/build-theme.mjs — do not edit manually. */
@layer reset {
${prose ?? ""}
${bootstrapProse ?? ""}
}

@layer astryx-theme {
${component ?? ""}
${bootstrapComponent ?? ""}
}
`;
}

const outputs = [
  {
    path: "../src/theme/academic.generated.css",
    css: renderThemeCss(academicTheme),
  },
  {
    path: "../src/theme/terminal.generated.css",
    css: renderThemeCss(
      terminalTheme,
      'html[data-appearance-theme="terminal"] [data-astryx-theme="ainigma-academic"]',
    ),
  },
];

for (const output of outputs) {
  const outputPath = fileURLToPath(new URL(output.path, import.meta.url));
  writeFileSync(outputPath, output.css);
  console.log(`wrote ${outputPath} (${output.css.length} bytes)`);
}
