keys:
  - &ainigma-data age1vvnxj8f3lrav00ujv7c59j5s55tsg5sza6jz48fa6wa5fes9gdusg53h3t

creation_rules:
  - path_regex: (^|/)supabase\.env$
    encrypted_regex: "^(POSTGRES_PASSWORD|JWT_SECRET|ANON_KEY|SERVICE_ROLE_KEY|SUPABASE_PUBLISHABLE_KEY|SUPABASE_SECRET_KEY|JWT_KEYS|JWT_JWKS|ANON_KEY_ASYMMETRIC|SERVICE_ROLE_KEY_ASYMMETRIC|DASHBOARD_PASSWORD|SECRET_KEY_BASE|REALTIME_DB_ENC_KEY|VAULT_ENC_KEY|PG_META_CRYPTO_KEY|LOGFLARE_PUBLIC_ACCESS_TOKEN|LOGFLARE_PRIVATE_ACCESS_TOKEN|S3_PROTOCOL_ACCESS_KEY_ID|S3_PROTOCOL_ACCESS_KEY_SECRET|MINIO_ROOT_PASSWORD|SMTP_PASS|OPENAI_API_KEY|GOOGLE_SECRET|GITHUB_SECRET|AZURE_SECRET|SMS_TWILIO_AUTH_TOKEN|SMS_TWILIO_MESSAGE_SERVICE_SID|SAML_PRIVATE_KEY)$"
    mac_only_encrypted: true
    key_groups:
      - age:
          - *ainigma-data
