# .sops.yaml
creation_rules:
  - path_regex: secrets/.*\.ya?ml$
    encrypted_regex: "^(GITHUB_APP_PRIVATE_KEY|GITHUB_TOKEN|DATABASE_URL|DATABASE_ADMIN_URL|TEST_EMAILS)$"
    age: >-
      age14h959770pjya6mjnljypl5dv5ysxfns6c9mkh2qzp24e2c6r7cnqd58y05
