# secrets/github-app.yaml
# ainigma-test org has ainigma-test-worker app
#
# Set when the test invitation and provision is run
RUN_EMAIL_TEST_SETUP: "1"

# === Offering and GitHub configuration
TEST_OFFERING_KEY: autumn-2026
TEST_ORGANIZATION_ID: "320458245"
TEST_ORGANIZATION_HANDLE: ainigma-test
TEST_EMAIL_DOMAIN: example.com
TEST_TEMPLATE_OWNER: ouspg
TEST_TEMPLATE_REPOSITORY: SoftwareHardwareSec-template
TEST_OWNER_AUTH_USER_ID: 50000000-0000-0000-0000-000000000001
# A real production worker URL with restricted access
DATABASE_URL: ""
# Full admin for local testing
DATABASE_ADMIN_URL: ENC[AES256_GCM,data:9EM/kcaZOEbRVi4KljE4AWwYuY5+mjLvuJdWjojtvGyWCAdTOfu+AxsC5Xd+yHoakIvdaGSD4g==,iv:cSnIgYAC7e4JKRNL1KPBKUA9Afjgvf70bSojIAOeEgA=,tag:wQM8hUv6hnpKbx5Yly5r5w==,type:str]
GITHUB_APP_CLIENT_ID: Iv23lipFCaZKpBEoWnR7
GITHUB_APP_INSTALLATION_ID: "158511434"
GITHUB_APP_PRIVATE_KEY: ENC[AES256_GCM,data:wYomv7SuDpITzTmCioV4zu2V4qstN95QMRI7nDdmxtdSvhC4hhxPv27XYO6k5cpdrwav2DFgqC/dZ7wZqNup7zSyiw8QPH7RotIAUTpQCydn4/ixA8casAOkW/gs/x3qq9PxcqzUIojRGddvEboXcFjjH312wjnBhN/wTpOWKji4z9e3SrGbWR/4CLSgvMdIvQW1k6ZatSFKXTihMjvl2wMik3tdB8Aeyk2gjjATQzMw3U+kb+jIgjETLH3MTO32QGCUDnawRCu/7GrRLFGmF1uvng+usSuMNLbtz3IjkaZvSznbvCRcOq1xIvoyqtCmRiBDGEJPj6iMqL7DMswG8XFtQG1sge1+ai1eqbwBJbAfDiBwlw7TK+V6StIP3S898ajORvW+mjrwsRg7gmPnFurD8X7UOAXpQcQW/Z8NfWrFSb+0lRnChCajqSKD0cbHemLEDf9JP4EKCLuQX9izOa3QAhhqh1tqfJ4TX2tgeKbTqsIDyJWAcMqJ1OcTwt2POOmCOGhYlXtX9zgz9uSJBajGx3xa1C+HbzgeUr8+fixN/ITqTKP4HWhYXHxXdE0tolX426FLihaUv03zurDrlG9btNEA/ZYr8DRibMXKyVa13D+Fb0/XYEDIKm7r4+KAUj1JMW+1X4qS+NltGYlB5Cx1yZCV4noqDXktDbBlk71Ofzzj1nw4tj9loZzhHuzj8uyY7/4nuyzEui01jpztFMN/J4zR977Sqfr+RZuOFOT67wUr1dwFvZAfBpeCebfFarEXU91BTlJ/v4j6+RXjxnv6HodQ6MA35NTenRXw4mcwu5lDvo2J9xZUCZbzS2zJUNjHH0CNQMVlNm/sEMAj3gpgHB5I848PNZVe8v0P1sPol95tu7bh43QrSXlphQwaCmtCyAvy83Uv/szqp58mq27tgBYhQ39bzJvLGuqBKBK06uALttuM5/+OcwQlsrDo74DrM+80WaukSOkm5JQ7Zp9k33x67KzZ9nFBT6fYKqiEj4ZKXJYzpFjYbu+AVOpzterpPlWMaZRsFEVAO5WULVuxgzgqOR+v/XnY7mVTqWJYjzM3dOFg9p643/fHPRHw5CutNWmp/7H41Q/ZgSYvmdBE92FYk2CuGoyIaelPZuAtFmYd7WOiflcKVb/0uoIKz8WUJg02VyeL4Z/XqYjkFDExBaGssjBOt5x2Ga9TdCmeINHypPZlMsun3hoc5AHRECFNQJwmqnr6Z/hH6avhu/8TDB6UVloPlDllJP+kEvIkiW637V/IDcWt5jXNQI6cABMfMtejJBrusNoWo3etYkdr118cm0Gl/MwTkZwQ17bCQVHVSmoghTX0gBQ0ViOOG+PD5WH55E2PES2EX59OvlsWlrv/Mk80lXzqR5XWJZPnZf14XyifBaf105HZG81lpcbFbo/GTHDaZypb/sgEQwDaboAhdqaBCPXLiLtfVprJQXoRh8sRl7sPTa+NMqwOnH/wsTr+Zl871H2DgSJIaceBg0u4wZVtExjX0Jj3JqWWhADWg6OBgVwXTyaje7i89wHv63J8m3iZ6o2Vhcd7qyVaylpTvfn60V9AEtHXXRmC/BItVj9RgbJ29BYoEjcrpMfs+Hjp0xE1xfoFp2DYK9NzTVnsx7vxblTVJ6AmGUqXqEGC/OVhf1FjJ5LlUewxiIuGIWoAmm8FdDwqy2DeJs+4i8SwDwYiEJjnVVNcWKEnW7O/eJzoK+xtjWz5rN5VVRZFeZkqefpqJKsAJNcNKU3l5yeciUI4KSqskQLHe/FAOivsR04p0qe3weJImr43Yxa68IzaHZjgXjenqG3kCFzLD0hSFFisc+AEHFyDHy9V3elK0/SPkXIVxP6O9l4n9Le3z98MfhnAfjHmZIBNVuJ67RZUhAbzR6jQxkhe6n19rsVK9e4pVLQhajO8OFRlL0YOt/DuT1UMHUO/NOEeyQD5YqM4puPyocEpGDC1cjqBYnvlKPPLaSs0s/LRYKWUpjQJ3q8qx9Sthi3D6SOyc5HyFDQ7/jiF9mK7BxHRieEykCcp6gcdH1J2EZ6d1uDeblTtEqMhICakvFJjwgxMTTLE8ytvrO8y3+9Rbn+7hjsQio8s08bmNdUW78tUYbUVQgclBFsCG3Mri9vaVUSSEmeDDJlIOi2td6Fxi5mv6o7X1++cFB1aC8+/he5vu0UuDhDLW4RkrLvCi5Z+xZOS+Aap16HujSFMl2lIAuS8c3a7bU3Hip5HBC0iCA==,iv:/CeVKvUBrAgGlU3aFdPtUJCfCzI/hOWUQrEmVNtoh7E=,tag:3F3ndLprAQ9Uelqz69lN+A==,type:str]
TEST_EMAILS: ENC[AES256_GCM,data:9OMQzeze3ZvaVVBPZXYKH5/KhIKQhnXltXKtfM2NdmAbFT/jk99NxLEbCPIc,iv:Sc38aYOx64D2LRec17ptRPCc15gDMDP61UCmyWc6QaA=,tag:CtTS0WpBZLswKSLrjP4a1w==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB5Si80QS9JTGJjU3FacDhj
        VVZiZVFhUEZYczVBeFJPUGJhN1BuMUZ3RjFjCmFhQWJ3RTJqTTR4YmJzMnVJU0xq
        dm1PdVpXTDZkUUt6THJiZ0FnWkxLUHMKLS0tIDdvVTdRSXIwNzRJUkZmVXlIdlRu
        SWlhRzAxU2MvOW9taStnN0ozc2oxYzgK+ZU59ew2u89gAOMhx/NxsqkxNnFGJKYY
        F/XrhdMKy7gilSfwsoRqy9Kzqv/x0ooZ7YHjnQOQZlxxbduJCAnIsg==
        -----END AGE ENCRYPTED FILE-----
      recipient: age14h959770pjya6mjnljypl5dv5ysxfns6c9mkh2qzp24e2c6r7cnqd58y05
  encrypted_regex: ^(GITHUB_APP_PRIVATE_KEY|GITHUB_TOKEN|DATABASE_URL|DATABASE_ADMIN_URL|TEST_EMAILS)$
  lastmodified: "2026-09-02T19:48:46Z"
  mac: ENC[AES256_GCM,data:lg10AjK5GigjoX03V/8Zdw6Lp5ST5qp6twxDoi3WvlbyR8Htm72i/vYRKH9Dje0AGdPXrHqf7Ldo6zipuzS9C/CjG4i0P3ey1Yxpe32G/2CcYwXU3q2tZGa89xvOYxu3xKXfNoWOpU56QlNr3bGn5BEYamxeqL+zlw4IRLGWWtQ=,iv:jwltIfftm0MF+rka3h/T+79XVoNrfnIKFJyXSYdU1l4=,tag:kjsmzvplkQWI92Ekuwaerw==,type:str]
  version: 3.13.3
